# Week 04: Basic NumPy

Make sure to have NumPy installed before proceeding!

## Importing Modules

To use more specialized functionality of Python, as well as third-party modules, you will need to know about the import statement.

In [1]:
# this will import the standard library module 'time'
import time

# its functions, classes and objects are available with the prefix 'time.'
print(time.localtime().tm_year)

# you can also import specific objects directly, in which case you don't need the prefix when using them
from time import localtime
print(localtime().tm_mon)

# lastly, the keyword 'as' is used to import something under a different name
# numpy, for instance, is usually import as 'np' to keep code shorter
import numpy as np
print(np.__version__)

2021
5
1.20.2


Import statements are also used to construct programs that consist of multiple files. As an exercise, try creating a file called `my_library.py` in the same directory as this notebook and giving it a function called `my_function` (it doesn't need to do much, perhaps print something). Then, try executing the cell below.

In [2]:
from my_library import my_function

my_function()

ModuleNotFoundError: No module named 'my_library'

It should be noted that when importing even just one object from a script, the entire script will be executed! Make sure to wrap any code that should *not* be executed when being imported in a block like this:

In [3]:
if __name__ == "__main__":
    # code here
    pass

## The `np.ndarray`

Everything in NumPy is built around the `ndarray`. Arrays, like lists, store values, but with two limitations:

1. They have a fixed datatype that is defined at their creation and must apply to all elements. Numpy usually detects an appropriate datatype automatically, but it can also be explicitly given with the `dtype` parameter.
2. They contain a fixed number of elements (also defined at creation)

In [4]:
# NumPy arrays can be created directly from Python sequences like lists or tuples
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
# ... or using helper functions
print(np.zeros(10))
print(np.ones(10))

print(np.arange(10))
print(np.arange(10, dtype=float))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [6]:
# you can access the datatype of any ndarray with the dtype attribute
arr1 = np.zeros(10)
arr2 = np.arange(10)

print(arr1.dtype, arr2.dtype)

float64 int64


Note that the datatypes used in NumPy arrays are a lot closer to those used in C and Java, a `uint32` array for example can't have numbers larger than 4,294,967,295, everything above "overflows" and starts again at 0.

## Multidimensional Arrays

One of the great advantages of NumPy arrays is that they are designed to be **multidimensional**. The vanilla Python equivalent would be **nested lists**, but here lies another difference: NumPy arrays must be **rectangular**, meaning for example all "rows" must have the same length.

In [7]:
# creating a multidimensional array from a nested list:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [8]:
# this won't produce the intended result because the nested list is not rectangular:
np.array([[1, 2, 3], [4]])

<ipython-input-8-6b2b97dcec9d>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, 2, 3], [4]])


array([list([1, 2, 3]), list([4])], dtype=object)

Most array-creating functions have a parameter `shape`, which can be used to specify the number of dimensions and their respective sizes. A shape is a `tuple` of `int`s, where each `int` determines the size of a dimension. The dimensions are ordered from **outermost** to **innermost** (when thinking of it as a nested array).

In [61]:
np.zeros(shape=(3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.ones(shape=(2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In fact, the positional parameter we used earlier *was* the shape parameter, so this also works:

In [11]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Arrays can be reshaped into different shapes. The number of dimensions may change, but the total number of elements may not. The use of a -1 signals NumPy to automatically determine the size of that dimension, given the other sizes and the total number of elements. There may only be a single -1 in each `reshape` call. 

In [12]:
array = np.arange(16)

print(array.reshape(4, 4), "\n")
print(array.reshape(2, -1), "\n")
print(array.reshape(16, 1), "\n")
print(array.reshape(1, 16))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]] 

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]] 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


The `.flatten()` method is equivalent to `.reshape(-1)`.

In [13]:
array = np.zeros((3, 3))
array.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

First, note that like most NumPy functions and methods, `.reshape` does **not** work **in-place**, meaning the original array is not changed. 

However, perhaps confusingly, `.reshape` also does **not** (necessarily) return a **copy** with changed dimensions of the array. Instead, it returns a new **view** of the same array, which means that if we mutate the original array, the view is also changed.

In [14]:
array = np.zeros(9)
view = array.reshape(3, 3)

print(array, "\n")
print(view)

[0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# now change only original array
array[4] = 42

# and print both again
print(array, "\n")
print(view)

[ 0.  0.  0.  0. 42.  0.  0.  0.  0.] 

[[ 0.  0.  0.]
 [ 0. 42.  0.]
 [ 0.  0.  0.]]


It's sometimes confusing when this kind of behavior occurs, some functions work like this and others don't. Aside from looking it up in the documentation, you can also use `array.copy()` if you want to make sure to work with a copy.

## Indexing Arrays

There are many ways to index the elements of a NumPy array, some of which will be shown in the next lecture. NumPy differentiates between *simple* and *advanced* indexing. Simple indexing can be thought of as a generalization of Python's slicing to multiple dimensions.

In [24]:
array = np.arange(16)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [25]:
# a single element
print(array[4])

4


In [26]:
# some slices
print(array[2:7])
print(array[:4])
print(array[-7:-2])

[2 3 4 5 6]
[0 1 2 3]
[ 9 10 11 12 13]


In [27]:
# extended slicing also works!
print(array[::-1])

[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


Slices can also be used for assignment. The right side of the assignment operator must be a Python sequence or a NumPy array with the correct datatype and shape (or a shape that is broadcastable to the required shape, see below for more on broadcasting).

In [124]:
array = np.arange(10)
array[3:7] = [42, 43, 44, 45]

print(array)

[ 0  1  2 42 43 44 45  7  8  9]


For higher-dimensional arrays, each dimension is indexed individually, separated by `,`. Again, dimensions are ordered from outermost to innermost.

In [30]:
array = np.arange(16).reshape(4, 4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [31]:
# a single element (row 1, column 2)
print(array[1, 2])

6


In [35]:
# some slices
print(array[0:2, 1:4], "\n")    # rows 0 and 1, columns 1, 2 and 3
print(array[:-1], "\n")         # rows 0, 1, and 2, no restriction on columns
print(array[:, :-1], "\n")      # no restriction on rows, columns 0, 1 and 2
print(array[::-1, ::2])         # all rows (but in reverse), every second column

[[1 2 3]
 [5 6 7]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]] 

[[12 14]
 [ 8 10]
 [ 4  6]
 [ 0  2]]


If you want your resulting slice to be of higher dimension than the original array, you can insert a `np.newaxis` object at the corresponding position. Alternatively, `None` does the same thing.

In [39]:
print(array[:, np.newaxis, :], "\n")
print(array[None, :, :])

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]

 [[12 13 14 15]]] 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


Lastly, for arrays with many dimensions, of which you only want to slice a couple, the use of the **ellipsis** object (literally `...`) makes sense. This lets NumPy automatically fill in as many `:, ` as needed to reach all dimensions.

In [111]:
array = np.arange(3 * 3 * 3 * 3).reshape(3, 3, 3, 3)

array[1:2, ...]

array([[[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In other languages you may have seen a syntax like this `array[row][column]` to access an element of a multidimensional array. While this technically works in NumPy, it is discouraged because it tends to be slower and less elegant. Consider using the `array[row, column]` syntax described above.

## Mathematical Operations

NumPy arrays work with the usual mathematical operators on an element-wise basis.

In [46]:
a = np.arange(16).reshape(4, 4)
b = np.ones((4, 4), dtype=np.int32)

print(a, "\n")
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [50]:
print(a + b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [52]:
# unlike vanilla Python, NumPy will only produce a warning when a division by zero occurs!
# the code will still run and result in 'inf' (or 'nan', if 0 / 0)
print(b / a)

[[       inf 1.         0.5        0.33333333]
 [0.25       0.2        0.16666667 0.14285714]
 [0.125      0.11111111 0.1        0.09090909]
 [0.08333333 0.07692308 0.07142857 0.06666667]]


<ipython-input-52-ffb769c58b4d>:3: RuntimeWarning: divide by zero encountered in true_divide
  print(b / a)


The `@` operator can be used to perform matrix multiplication.

In [55]:
matrix1 = np.arange(4).reshape(2, 2)
matrix2 = np.ones((2, 2))

print(matrix1 @ matrix2)

[[1. 1.]
 [5. 5.]]


For the element-wise operations, it is not necessary that the two operands have the same dimensions. For example, it's possible to multiply an entire array element wise with a scalar.

In [58]:
print(np.ones((3, 3)) * 4)

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


However, something like this also works:

In [59]:
array1 = np.ones((3, 3))    # shape: (3, 3)
array2 = np.arange(3)       # shape: (3)

print(array1 * array2)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


In both cases, NumPy automatically performs what's called **Broadcasting**. Broadcasting tries to expand the dimensions of both operands until they match. This is not always possible. To understand what's going on we have to look at the steps by which NumPy performs broadcasting.#

**1. Step** If the arrays have different numbers of dimensions, the smaller shape is padded with ones on its left side.

    Example: (5 x 3) + (3) → (5 x 3) + (1 x 3)


**2. Step** If the number of the dimensions matches, but the size of a dimension does not, dimensions with the size of 1 are expanded.

    Example: (5 x 3) + (1 x 3) → (5 x 3) + (5 x 3)

**3. Step** If the shapes of the arrays still defer after applying the steps 1 and 2, a broadcasting error is raised.

NumPy documentation on broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html

![Broadcasting Illustration](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

Image Source: https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png

## Element-wise Functions

NumPy provides many functions that take entire arrays as inputs and perform element-wise operations.

A special type of element-wise functions are called **ufuncs** (universal functions). If given multiple arguments, they will perform automatic broadcasting where required.


In [63]:
array = np.arange(9).reshape(3, 3)

print(np.sin(array))

[[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825]]


A list of all available ufuncs can be found here:
https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

A complete list of all NumPy functions (many of which work element-wise) can be found here:
https://numpy.org/doc/stable/reference/routines.html


## Constants

Of course, NumPy also has common constants used in mathematics like $\pi$ and $e$:

In [66]:
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


## `np.linspace`

`np.linspace(start, stop, num)` is a useful function that, similarly to `np.arange`, creates an array spanning from `start` to `stop`. However, the third parameter `num` determines how many evenly distributed elements the array should have.

In [69]:
print(np.linspace(0, 1, 11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


## Aggregation Functions

Contrary to element-wise functions, aggregation functions reduce the dimensionality of an array. Examples include `np.mean`, `np.sum` and `np.max`/`np.min`.

They all have a special parameter `axis`, which specifies along which dimension (or which dimensions) to perform the aggregation.

In [72]:
array = np.arange(16).reshape(4, 4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [75]:
print(np.sum(array, axis=0))       # sums of all columns
print(np.sum(array, axis=1))       # sums of all rows
print(np.sum(array, axis=(0, 1)))  # sum over dimensions 0 and 1
print(np.sum(array))               # sum over all dimensions

[24 28 32 36]
[ 6 22 38 54]
120
120


A special aggregation function is `np.cumsum`, which like `np.sum` sums along one or more axes, but returns all intermediate results in an array of the same shape as the input array.

In [77]:
print(np.cumsum(array, axis=1))

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]
 [12 25 39 54]]


A less known trick is that every *ufunc* (see above) can be turned into a aggregation function using `ufunc.reduce`.

In [79]:
print(np.multiply.reduce(array, axis=0))

[   0  585 1680 3465]


## Comparing Arrays

Like mathematical operators, comparison operators also work element-wise with NumPy Arrays. They will return a boolean array containing the result of each comparison.

In [82]:
array1 = np.arange(5)
array2 = array1.copy()
array2[3] = 42

print(array1 == array2)

[ True  True  True False  True]


`np.all` is an aggregation function that returns `True` if and only if all values in an array (or along an axis if an `axis` is specified) are `True`. To compare two entire arrays as a whole, it seems intuitive to do something like this:

In [83]:
np.all(array1 == array2)

False

While this usually works, in some edge cases this can produce unintended results. It is safer to use NumPy's provided function `np.array_equal`.

In [84]:
np.array_equal(array1, array2)

False

A similar function is `np.allclose`, which returns `True` if two arrays have almost the same value in all places. An error margin can be specified.

In [87]:
epsilon = 1e-10

array3 = array1 + epsilon

print(np.array_equal(array1, array3))
print(np.allclose(array1, array3))

False
True


## Performance

There is nothing you can do with NumPy that you couldn't in principle also do with normal Python, but by now you have hopefully noticed the convenience of NumPy when working with numerical data. In addition to convenience, NumPy also offers significantly better performance when working with large amounts of numbers.

As a quick demonstration, let's compute the mean of the integers from 1 to 10,000,000 using plain Python and using NumPy.

In [118]:
def compute_mean_naive(data):
    mean = 0
    
    for d in data:
        mean += d
    
    mean /= len(data)
    
    return mean

def compute_mean_pythonic(data):
    return sum(data) / len(data)

def compute_mean_numpy(data):
    return np.mean(data)

In [119]:
data_python = list(range(10_000_000))
data_numpy = np.array(data_python)

In [122]:
%timeit compute_mean_naive(data_python)
%timeit compute_mean_pythonic(data_python)
%timeit compute_mean_numpy(data_numpy)

332 ms ± 14.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
61.8 ms ± 760 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
9.75 ms ± 14.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


As is evident from the results, using Python's built-in functions already drastically improves upon a naive approach, but NumPy is another order of magnitude faster.

## Random Numbers

The module `numpy.random` provides options for generating pseudo-random numbers. For instance, there are various distributions to sample from.

In [93]:
uniform = np.random.uniform(0, 1, size=10)
normal = np.random.normal(0, 1, size=10)
gumbel = np.random.gumbel(0, 1, size=10)

In some cases, you may want the generated random numbers to be the same every time you run your program. In that case, you can set a seed like this before generating.

In [97]:
np.random.seed(42)
print(np.random.uniform(0, 1, size=10))    # these will always be the same

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]


`np.random.shuffle` and `np.random.permutation` both shuffle an array, however the first works in-place while the latter returns a copy.

In [98]:
array1 = np.arange(10)
np.random.shuffle(array1)

print(array1)

array2 = np.arange(10)
print(np.random.permutation(array2))

[8 2 0 6 7 9 3 1 4 5]
[1 7 6 2 8 0 3 4 5 9]


`np.random.choice` allows to pick random elements from an array.

In [112]:
array = np.array(list("Python"))

print(np.random.choice(array, size=3, replace=False))

['o' 't' 'n']


## More NumPy

NumPy has much more to offer. Next week, we will discuss a couple features that were left out this time, most notably advanced indexing methods.

https://numpy.org/doc/